version: "3"

services:
  app:
    build: .
    container_name: app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - appversion: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
