exports.getTasks = catchAsync(async (req, res, next) => {

  const tasks = await TaskService.getTasks(
    req.user.id,
    req.query
  );

  res.status(200).json({
    status: "success",
    results: tasks.length,
    data: tasks,
  });
});
events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://app:3000;
    }
  }
}
